# Generated by Django 6.0.3 on 2026-03-12 23:07

import django.core.validators
import relacionamentos.validators.validacao_cpf
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Insira o nome da pessoa', max_length=100, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Nome')),
                ('data_nascimento', models.DateField(help_text='Insira a data de nascimento da pessoa', verbose_name='Data de Nascimento')),
                ('cpf', models.CharField(help_text='Insira o CPF da pessoa', max_length=11, unique=True, validators=[django.core.validators.MinLengthValidator(11), relacionamentos.validators.validacao_cpf.validacao_cpf], verbose_name='CPF')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
