# Generated by Django 6.0.3 on 2026-03-17 01:08

import datetime
import django.core.validators
import django.db.models.deletion
import relacionamentos.validators.validacao_cpf
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Insira o nome da pessoa', max_length=100, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Nome')),
                ('data_nascimento', models.DateField(help_text='Insira a data de nascimento da pessoa', verbose_name='Data de Nascimento')),
                ('cpf', models.CharField(help_text='Insira o CPF da pessoa', max_length=11, unique=True, validators=[django.core.validators.MinLengthValidator(11), relacionamentos.validators.validacao_cpf.validacao_cpf], verbose_name='CPF')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Digite o nome da disciplina', max_length=100, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Nome da Disciplina')),
                ('sigla', models.CharField(help_text='Digite a sigla da disciplina', max_length=5, unique=True, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Sigla da Disciplina')),
                ('semestre', models.IntegerField(help_text='Digite o semestre da disciplina', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Semestre da Disciplina')),
                ('ementa', models.TextField(help_text='Digite a ementa da disciplina', verbose_name='Ementa da Disciplina')),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='relacionamentos.pessoa')),
                ('email', models.EmailField(help_text='E-mail institucional do aluno', max_length=254, unique=True, verbose_name='E-mail')),
                ('cod', models.CharField(help_text='Digite a matricula do aluno', max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Matricula')),
            ],
            options={
                'abstract': False,
            },
            bases=('relacionamentos.pessoa',),
        ),
        migrations.CreateModel(
            name='Reporter',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='relacionamentos.pessoa')),
                ('email', models.EmailField(help_text='Insira o institucional', max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Email do Repórter')),
            ],
            options={
                'abstract': False,
            },
            bases=('relacionamentos.pessoa',),
        ),
        migrations.CreateModel(
            name='Passaporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text='Número do passaporte', max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='Numero do Passaporte')),
                ('emissao', models.DateField(help_text='Data de emissão do passaporte', validators=[django.core.validators.MinValueValidator(datetime.date.today)], verbose_name='Data de Emissao')),
                ('vencimento', models.DateField(help_text='Data de vencimento do passaporte', verbose_name='Data de Vencimento')),
                ('pessoa', models.OneToOneField(help_text='Pessoa associada ao passaporte', on_delete=django.db.models.deletion.CASCADE, to='relacionamentos.pessoa')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Revista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Insira o nome da revista', max_length=100, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Nome da Revista')),
                ('edicao', models.IntegerField(help_text='Insira a edição da revista', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Edição da Revista')),
            ],
            options={
                'unique_together': {('nome', 'edicao')},
            },
        ),
        migrations.CreateModel(
            name='Reportagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Insira o título da reportagem', max_length=200, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Título da Reportagem')),
                ('publicacao', models.DateField(help_text='Insira a data de publicação da reportagem', validators=[django.core.validators.MinValueValidator(datetime.date.today)], verbose_name='Data de Publicação')),
                ('revistas', models.ManyToManyField(help_text='Revistas associadas à reportagem', to='relacionamentos.revista')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_matricula', models.DateField(help_text='Digite a data de matrícula do aluno', verbose_name='Data de Matrícula')),
                ('nota', models.FloatField(help_text='Digite a nota do aluno na disciplina', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)], verbose_name='Nota')),
                ('frequencia', models.FloatField(help_text='Digite a frequência do aluno na disciplina', verbose_name='Frequência')),
                ('status', models.CharField(choices=[('Aprovado', 'Aprovado'), ('Reprovado', 'Reprovado'), ('Matriculado', 'Matriculado'), ('Trancado', 'Trancado'), ('Em Exame', 'Em Exame'), ('Aprovado em Exame', 'Aprovado em Exame')], default='Matriculado', help_text='Digite o status da matrícula do aluno na disciplina', max_length=20)),
                ('disciplina', models.ForeignKey(help_text='Selecione a disciplina para a matrícula', on_delete=django.db.models.deletion.PROTECT, to='relacionamentos.disciplina')),
                ('aluno', models.ForeignKey(help_text='Selecione o aluno para a matrícula', on_delete=django.db.models.deletion.PROTECT, to='relacionamentos.aluno')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='aluno',
            name='disciplinas',
            field=models.ManyToManyField(help_text='Selecione as disciplinas do aluno', through='relacionamentos.Matricula', through_fields=('aluno', 'disciplina'), to='relacionamentos.disciplina'),
        ),
        migrations.CreateModel(
            name='Artigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Insira o título do artigo', max_length=100, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Título do Artigo')),
                ('publicacao', models.DateField(help_text='Insira a data de publicação do artigo', validators=[django.core.validators.MinValueValidator(datetime.date.today)], verbose_name='Data de Publicação')),
                ('autor', models.ForeignKey(help_text='Selecione o autor do artigo', on_delete=django.db.models.deletion.CASCADE, to='relacionamentos.reporter', verbose_name='Autor do Artigo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
