# Generated by Django 6.0.3 on 2026-03-12 23:43

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relacionamentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passaporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text='Número do passaporte', max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='Numero do Passaporte')),
                ('emissao', models.DateField(help_text='Data de emissão do passaporte', validators=[django.core.validators.MinValueValidator(datetime.date.today)], verbose_name='Data de Emissao')),
                ('vencimento', models.DateField(help_text='Data de vencimento do passaporte', verbose_name='Data de Vencimento')),
                ('pessoa', models.OneToOneField(help_text='Pessoa associada ao passaporte', on_delete=django.db.models.deletion.CASCADE, to='relacionamentos.pessoa')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
