# Generated by Django 6.0.3 on 2026-03-31 01:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relacionamentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Insira o nome da cidade', max_length=100, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Nome da Cidade')),
                ('estado', models.CharField(help_text='Insira a sigla do estado', max_length=2, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Estado')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Esporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Insira o nome do esporte', max_length=20, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='Nome do Esporte')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Insira o nome do time', max_length=20, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Nome do Time')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pessoaa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Insira o nome completo da pessoa', max_length=40, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Nome Completo')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], help_text='Insira o sexo da pessoa (M/F)', max_length=1, validators=[django.core.validators.MinLengthValidator(1)])),
                ('idade', models.IntegerField(help_text='Insira a idade da pessoa', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Idade')),
                ('renda', models.DecimalField(decimal_places=2, help_text='Insira a renda da pessoa', max_digits=10, verbose_name='Renda')),
                ('cidade_residencia', models.ForeignKey(blank=True, help_text='Selecione a cidade de residência da pessoa', null=True, on_delete=django.db.models.deletion.SET_NULL, to='relacionamentos.cidade', verbose_name='Cidade de Residência')),
                ('esporte_praticado', models.ForeignKey(blank=True, help_text='Selecione o esporte praticado pela pessoa', null=True, on_delete=django.db.models.deletion.SET_NULL, to='relacionamentos.esporte', verbose_name='Esporte Praticado')),
                ('time_torce', models.ForeignKey(blank=True, help_text='Selecione o time de futebol favorito da pessoa', null=True, on_delete=django.db.models.deletion.SET_NULL, to='relacionamentos.time', verbose_name='Time de Futebol')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
