# Generated by Django 6.0.4 on 2026-05-05 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relacionamentos', '0002_cidade_esporte_time_pessoaa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='aluno',
            field=models.ForeignKey(help_text='Selecione o aluno para a matrícula', on_delete=django.db.models.deletion.CASCADE, to='relacionamentos.aluno'),
        ),
    ]
