# Generated by Django 6.0.3 on 2026-03-13 00:49

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relacionamentos', '0003_reporter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Insira o título do artigo', max_length=100, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Título do Artigo')),
                ('publicacao', models.DateField(help_text='Insira a data de publicação do artigo', validators=[django.core.validators.MinValueValidator(datetime.date.today)], verbose_name='Data de Publicação')),
                ('autor', models.ForeignKey(help_text='Selecione o autor do artigo', on_delete=django.db.models.deletion.CASCADE, to='relacionamentos.reporter', verbose_name='Autor do Artigo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
