# Generated by Django 6.0.3 on 2026-03-13 01:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relacionamentos', '0004_artigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Revista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Insira o nome da revista', max_length=100, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Nome da Revista')),
                ('edicao', models.IntegerField(help_text='Insira a edição da revista', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Edição da Revista')),
            ],
            options={
                'unique_together': {('nome', 'edicao')},
            },
        ),
    ]
