# Generated by Django 6.0.3 on 2026-03-13 01:26

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relacionamentos', '0005_revista'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reportagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Insira o título da reportagem', max_length=200, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Título da Reportagem')),
                ('publicacao', models.DateField(help_text='Insira a data de publicação da reportagem', validators=[django.core.validators.MinValueValidator(datetime.date.today)], verbose_name='Data de Publicação')),
                ('revistas', models.ManyToManyField(help_text='Revistas associadas à reportagem', to='relacionamentos.revista')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
