from .base_model import *
from .pessoa import *
from .passaporte import *
from .reporter import *
from .artigo import *
from .revista import *
from .reportagem import *
from .disciplina import *
from .aluno import *
from .matricula import *
from .Esporte_csv import *
from .Cidade_csv import * 
from .Pessoa_csv import *
from .Time_csv import *