from .base_model import *
from .pessoa import *
from .passaporte import *
from .reporter import *
from .artigo import *
from .revista import *
from .reportagem import *
from .disciplina import *
from .aluno import *
from .matricula import *
