# Generated by Django 4.2.28 on 2026-06-24 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0002_problema_delete_teste'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problema',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='problema',
            name='nivel',
            field=models.IntegerField(choices=[('1', 'Um'), ('2', 'Dois'), ('3', 'Tres'), ('4', 'Quatro'), ('5', 'Cinco'), ('6', 'Seis'), ('7', 'Sete'), ('8', 'Oito'), ('9', 'Nove'), ('10', 'Dez')], default='1', help_text='Escolha o nivel do problema', verbose_name='Nivel'),
        ),
    ]
