# Generated by Django 4.2.28 on 2026-06-24 23:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0003_alter_problema_id_alter_problema_nivel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problema',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='problema',
            name='titulo',
            field=models.CharField(help_text='Titulo do problema', max_length=100, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Titulo'),
        ),
    ]
